global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: qdrant
    metrics_path: /metrics
    static_configs:
      - targets:
          - qdrant:6333
  - job_name: meilisearch
    metrics_path: /metrics
    static_configs:
      - targets:
          - meilisearch:7700
  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets:
          - traefik:8082
