global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets:
          - traefik:8082
  - job_name: qdrant
    metrics_path: /metrics
    static_configs:
      - targets:
          - qdrant:6333
