version: '3.8'

services:
  # Chroma Vector Database - Recommended for Development
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma-vectordb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
      - ./chroma_config:/chroma/config
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["http://localhost:3000"]
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.token_authn
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - vector-network

  # Qdrant Vector Database - Recommended for Production  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-vectordb
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config:/qdrant/config
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    command:
      - "./qdrant"
      - "--config-path"
      - "config/production.yaml"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - vector-network

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: vector-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - vector-network

  # Nginx reverse proxy for production deployments
  nginx:
    image: nginx:alpine
    container_name: vector-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/ssl:ro
    depends_on:
      - chroma
      - qdrant
    restart: unless-stopped
    networks:
      - vector-network
    profiles:
      - production

volumes:
  chroma_data:
    driver: local
  qdrant_data:
    driver: local
  redis_data:
    driver: local

networks:
  vector-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16